# .github/workflows/main.yml

name: Scheduled and On-Demand Data Refresh

on:
  schedule:
    # (你的定时规则保持不变)
    - cron: '30,45 1 * * 1-5'
    - cron: '0,15,30,45 2-6 * * 1-5'
    - cron: '0,15,30,45 7-8 * * 1-5'
    
  workflow_dispatch:
    inputs:
      trigger_source:
        description: 'Source of the trigger (e.g., "manual" or "api_call")'
        required: false
        default: 'manual_ui'
      # <-- [MANDATORY] 新增 dynamiclist 输入的定义 -->
      dynamiclist:
        description: 'A JSON string of A-share stock codes (e.g., ["000001", "600519"])'
        required: false
        default: ''
      # <-- [MANDATORY] 新增 dynamicHKlist 输入的定义 -->
      dynamicHKlist:
        description: 'A JSON string of HK-share stock codes (e.g., ["00700", "09988"])'
        required: false
        default: ''

jobs:
  build-and-commit:
    name: Build Data and Commit to Repo
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Log trigger source
        run: |
          echo "Workflow triggered by: ${{ github.event.inputs.trigger_source || github.event_name }}"

      - name: Run data fetching script
        # <-- [RECOMMENDED] 使用 env 块将输入安全地传递为环境变量 -->
        env:
          INPUT_DYNAMICLIST: ${{ github.event.inputs.dynamiclist }}
          INPUT_DYNAMICHKLIST: ${{ github.event.inputs.dynamicHKlist }}
        run: python api/index.py

      - name: Commit and push if changed
        env:
          COMMIT_MSG: "chore(data): Update market data (Trigger: ${{ github.event.inputs.trigger_source || github.event_name }})"
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add data/
          git diff --staged --quiet || (git commit -m "$COMMIT_MSG" && git push)
          echo "Data commit process finished."
