      - name: Merge Excel files
        run: |
          # The inline Python script remains the same, but paths are simpler
          python << 'EOF'
import pandas as pd
import os

print("Starting Excel merge process...")

# Define file paths (they are now in the same checkout)
original_file = 'data/AIPEPortfolio.xlsx'
new_data_file = 'data/AIPEPortfolio_new.xlsx'

try:
    df_dazhi_orig = pd.read_excel(original_file, sheet_name='大智投资组合')
    df_dacheng_orig = pd.read_excel(original_file, sheet_name='大成投资组合')
    df_my_orig = pd.read_excel(original_file, sheet_name='我的投资组合')
    print(f"Successfully loaded existing portfolio from {original_file}")
except FileNotFoundError:
    print(f"'{original_file}' not found. Will create a new one.")
    df_dazhi_orig = pd.DataFrame()
    df_dacheng_orig = pd.DataFrame()
    df_my_orig = pd.DataFrame()

df_dazhi_new = pd.read_excel(new_data_file, sheet_name='大智投资组合')
df_dacheng_new = pd.read_excel(new_data_file, sheet_name='大成投资组合')
df_my_new = pd.read_excel(new_data_file, sheet_name='我的投资组合')
print(f"Successfully loaded new data from {new_data_file}")

df_dazhi_combined = pd.concat([df_dazhi_orig, df_dazhi_new], ignore_index=True)
df_dacheng_combined = pd.concat([df_dacheng_orig, df_dacheng_new], ignore_index=True)
df_my_combined = pd.concat([df_my_orig, df_my_new], ignore_index=True)
print("Dataframes concatenated.")

with pd.ExcelWriter(original_file, engine='openpyxl') as writer:
    df_dazhi_combined.to_excel(writer, sheet_name='大智投资组合', index=False)
    df_dacheng_combined.to_excel(writer, sheet_name='大成投资组合', index=False)
    df_my_combined.to_excel(writer, sheet_name='我的投资组合', index=False)

print(f"Successfully wrote combined data back to {original_file}")
EOF
